/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BarraLateral: typeof import('./src/components/BarraLateral.vue')['default']
    CadastroCliente: typeof import('./src/components/CadastroCliente.vue')['default']
    ConsultaCliente: typeof import('./src/components/ConsultaCliente.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
